# API

## 1. Admin

### 1.1 Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "your-email",
    "password": "your-password",
    "rememberMe": false
}

### 1.2 Register / Signup
POST http://localhost:9091/admin/register-admin
Content-Type: application/json

{
    "email": "your-email",
    "password": "your-password",
    "firstname": "your-firstname",
    "lastname": "your-lastname"
}

### 1.3 Forgot
POST http://localhost:9091/admin/forgot-password
Content-Type: application/json

{
    "email": "your-email"
}

### 1.3.1 Reset Password
POST http://localhost:9091/admin/reset-password
Content-Type: application/json

{
    "resetPasswordToken": "your-reset-token",
    "password": "your-new-password"
}

### 1.4 Profile
GET http://localhost:9091/admin/users/me
Authorization: Bearer <your-token>

## 2. User

### 2.1 Login
POST http://localhost:9091/api/auth/local
Content-Type: application/json

{
    "identifier": "your-email",
    "password": "your-password"
}

### 2.2 Register / Signup
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
    "username": "your-username",
    "email": "your-email",
    "password": "your-password"
}


### 2.3 Forgot
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
    "email": "your-email"
}

### 2.3.1 Reset Password
POST http://localhost:9091/api/auth/reset-password
Content-Type: application/json

{
    "code": "your-reset-code",
    "password": "your-new-password",
    "passwordConfirmation": "your-new-password"
}

### 2.4 Profile
GET http://localhost:9091/api/users/me
Authorization: Bearer <your-token>
